### ISSUE TITLE
Incorporating glad bot into my mod

### ISSUE THREAD

**Issue by voivodpl** [earth-metal/ugladq2#2]
Hi. I have a problem incorporating gladiator bot into my mod(REdux). I used knightmare source. Could you provide some help ? I'm beginner in C++ but have major Pawn experience.

I used and started to merge the original gladiator bot source and last known error to fix is:
`p_view.obj : error LNK2019: unresolved external symbol _ShowMenu referenced in function _ClientEndServerFrame`

**Comment by earth-metal** [comment]
Based on the error I'm guessing you don't have an include for p_menulib.c's functions in p_view.c.

In the Gladiator source,  the ShowMenu function is defined in p_menulib.c, and made available in other compiled objects by adding p_menulib.h into g_local.h.
